name: Campaign
description: Track the progress of a Campaign
title: "[campaign]: "
labels: ["Campaigns"]
body:
  - type: markdown
    attributes:
      value: "## Epic"
  - type: markdown
    attributes:
      value: "- #787"
  - type: markdown
    attributes: 
      value: "## Description"
  - type: markdown
    attributes:
      value: "### Campaign"
  - type: markdown
    attributes:
      value: "<!--- Insert campaign acronym and long name --->"
  - type: markdown
    attributes:
      value: "### Content Notes"
  - type: markdown
    attributes:
      value: "<!--- Provide content notes document link here --->"
  - type: markdown
    attributes: 
      value: "## Progress"
  - type: markdown
    attributes:
      value: "### Compile"
  - type: markdown
    attributes:
      value: "*Compiler: <name>*"
  - type: markdown
    attributes:
      value: "<!--- Insert compiler name after colon --->"
  - type: checkboxes
    id: compiler-checklist
    label: "Check off the following as they are completed:"
    attributes:
      options:
        - label: Campaign
        - label: Platform
        - label: Deployment
        - label: IOP/SE
        - label: CDPI
        - label: Partner Org
        - label: DOI
  - type: markdown
    attributes:
      value: "### Review"
  - type: markdown
    attributes:
      value: "*Reviewer: <name>*"
  - type: markdown
    attributes:
      value: "<!--- Insert reviewer name after colon --->"
  - type: checkboxes
    id: reviewer-checklist
    label: "Check off the following as they are completed:"
    attributes:
      options:
        - label: Campaign
        - label: Platform
        - label: Deployment
        - label: IOP/SE
        - label: CDPI
        - label: Partner Org
        - label: DOI
  - type: markdown
    attributes:
      value: "### Approve"
  - type: markdown
    attributes:
      value: "*Approver: <name>*"
  - type: markdown
    attributes:
      value: "<!--- Insert approver name after colon --->"
  - type: checkboxes
    id: approver-checklist
    label: "Check off the following as they are completed:"
    attributes:
      options:
        - label: Campaign
        - label: Platform
        - label: Deployment
        - label: IOP/SE
        - label: CDPI
        - label: Partner Org
        - label: DOI
