name: Campaign
description: Track the progress of a Campaign
title: "[campaign]: "
label: 'Campaigns'
body:
  - type: checkboxes
    id: approver-checklist
    attributes:
      options:
        - label: Campaign
        - label: Platform
        - label: Deployment
        - label: IOP/SE
        - label: CDPI
        - label: Partner Org
        - label: DOI
